export const MEMBER_CLIENT = '2'

export const MERCHANT_CLIENT = '3'

export const MEMBER_SUBSCRIBE_SMALL = '4'

export const MEMBER_SUBSCRIBE_PRIVATE = '5'

export const MENU_TYPES = {MEMBER_CLIENT, MERCHANT_CLIENT, MEMBER_SUBSCRIBE_SMALL, MEMBER_SUBSCRIBE_PRIVATE}
